# Site settings
title: PitchLinkX
email: perfectpitchbw@gmail.com
description: "PitchLinX Website"
baseurl: ""
url: ""

twitter_username: pitchlinkx
github_username: pitchlinkx

# Build settings
markdown: kramdown
