# Site settings
title: Perfect Pitch
email: perfectpitch.bw@gmail.com
description: ""
baseurl: "" 
url: ""

twitter_username: perfectpitch20
github_username: perfectpitchbw

# Build settings
markdown: kramdown
