# Site settings
title: PitchLinkX
email:perfectpitchbw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: ""

twitter_username:pitchlinkx
github_username:pitchlinkx

# Build settings
markdown: kramdown
